# Generated by Django 4.2.7 on 2023-11-19 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_coupon_order_discounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discounts',
            new_name='discount',
        ),
    ]
